### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/coloring-book#98]
When Painting, this occurred:

```
W/System: A resource failed to call end. 
E/Parcel: Class not found when unmarshalling: G
    java.lang.ClassNotFoundException: G
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2811)
        at android.os.Parcel.readParcelable(Parcel.java:2765)
        at org.androidsoft.coloring.util.images.PreparedUriImage$1.createFromParcel(PreparedUriImage.java:64)
        at org.androidsoft.coloring.util.images.PreparedUriImage$1.createFromParcel(PreparedUriImage.java:61)
        at android.os.Parcel.readParcelable(Parcel.java:2774)
        at android.os.Parcel.readValue(Parcel.java:2668)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3037)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.Bundle.getParcelable(Bundle.java:940)
        at android.content.Intent.getParcelableExtra(Intent.java:7473)
        at org.androidsoft.coloring.ui.activity.PaintActivity.onActivityResult(PaintActivity.java:240)
        at android.app.Activity.dispatchActivityResult(Activity.java:7462)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: G
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2811) 
        at android.os.Parcel.readParcelable(Parcel.java:2765) 
        at org.androidsoft.coloring.util.images.PreparedUriImage$1.createFromParcel(PreparedUriImage.java:64) 
        at org.androidsoft.coloring.util.images.PreparedUriImage$1.createFromParcel(PreparedUriImage.java:61) 
        at android.os.Parcel.readParcelable(Parcel.java:2774) 
        at android.os.Parcel.readValue(Parcel.java:2668) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3037) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:232) 
        at android.os.Bundle.getParcelable(Bundle.java:940) 
        at android.content.Intent.getParcelableExtra(Intent.java:7473) 
        at org.androidsoft.coloring.ui.activity.PaintActivity.onActivityResult(PaintActivity.java:240) 
        at android.app.Activity.dispatchActivityResult(Activity.java:7462) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4391) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.quelltext.coloring, PID: 11371
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { (has extras) }} to activity {eu.quelltext.coloring/org.androidsoft.coloring.ui.activity.PaintActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: G
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: G
        at android.os.Parcel.readParcelableCreator(Parcel.java:2839)
        at android.os.Parcel.readParcelable(Parcel.java:2765)
        at org.androidsoft.coloring.util.images.PreparedUriImage$1.createFromParcel(PreparedUriImage.java:64)
        at org.androidsoft.coloring.util.images.PreparedUriImage$1.createFromParcel(PreparedUriImage.java:61)
        at android.os.Parcel.readParcelable(Parcel.java:2774)
        at android.os.Parcel.readValue(Parcel.java:2668)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3037)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.Bundle.getParcelable(Bundle.java:940)
        at android.content.Intent.getParcelableExtra(Intent.java:7473)
        at org.androidsoft.coloring.ui.activity.PaintActivity.onActivityResult(PaintActivity.java:240)
        at android.app.Activity.dispatchActivityResult(Activity.java:7462)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by niccokunzmann** [comment]
This happens when choosing an DrawableResourceImage is transferred.
